article: https://www.bigclown.com/doc/projects/radio-co2-monitor/
video: https://youtu.be/jGxjl5v7kqE
images:
  - title:
    url: https://www.bigclown.com/kits/co2-monitor/main.png
assembly:
  - name: BigClown CO2 Module
  - name: BigClown Core Module
  - name: BigClown Battery Module
  - name: BigClown Temperature Tag
    optional: true
  - name: BigClown Humidity Tag
    optional: true
  - name: BigClown Barometer Tag
    optional: true
