article: https://www.bigclown.com/doc/projects/wireless-co2-monitor/
assembly:
  - name: BigClown Button Module
  - name: BigClown CO2 Module
  - name: BigClown Core Module
  - name: BigClown Battery Module
